CREATE DATABASE IF NOT EXISTS barber_shop_db;
USE barber_shop_db;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(13) UNIQUE,
  passwordHash VARCHAR(255) NOT NULL,
  emailVerified BOOLEAN DEFAULT FALSE,
  emailVerifyCodeHash VARCHAR(255),
  emailVerifyCodeExpires DATETIME,
  resetCodeHash VARCHAR(255),
  resetCodeExpires DATETIME,
  avatarUrl MEDIUMTEXT,
  avatarData LONGTEXT,
  role ENUM('user', 'admin') DEFAULT 'user',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS pending_registrations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(13) UNIQUE,
  passwordHash VARCHAR(255) NOT NULL,
  verifyCodeHash VARCHAR(255) NOT NULL,
  verifyCodeExpires DATETIME NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS services (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  price DECIMAL(10, 2) NOT NULL,
  durationMin INT DEFAULT 60,
  imageUrl MEDIUMTEXT,
  imageData LONGTEXT,
  category VARCHAR(100),
  isPopular BOOLEAN DEFAULT FALSE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS barbers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(150) NOT NULL,
  specialty VARCHAR(120),
  experienceYears INT DEFAULT 0,
  rating DECIMAL(3, 2) DEFAULT 5.00,
  bio TEXT,
  imageUrl MEDIUMTEXT,
  imageData LONGTEXT,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS barber_services (
  barberId INT NOT NULL,
  serviceId INT NOT NULL,
  PRIMARY KEY (barberId, serviceId),
  FOREIGN KEY (barberId) REFERENCES barbers(id) ON DELETE CASCADE,
  FOREIGN KEY (serviceId) REFERENCES services(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS records (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  barberId INT NOT NULL,
  serviceId INT NOT NULL,
  appointmentAt DATETIME NOT NULL,
  comment TEXT,
  status ENUM('active', 'completed', 'cancelled') DEFAULT 'active',
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (barberId) REFERENCES barbers(id) ON DELETE CASCADE,
  FOREIGN KEY (serviceId) REFERENCES services(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS favorites (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL,
  serviceId INT NOT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_user_service_fav (userId, serviceId),
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (serviceId) REFERENCES services(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS reviews (
  id INT AUTO_INCREMENT PRIMARY KEY,
  recordId INT NULL,
  userId INT NULL,
  serviceId INT NULL,
  barberId INT NOT NULL,
  authorName VARCHAR(120) NOT NULL,
  rating INT NULL,
  text TEXT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_review_record (recordId),
  FOREIGN KEY (recordId) REFERENCES records(id) ON DELETE SET NULL,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (serviceId) REFERENCES services(id) ON DELETE SET NULL,
  FOREIGN KEY (barberId) REFERENCES barbers(id) ON DELETE CASCADE
);

